
#ifndef CELLSINTERLINKED_PACKETEVENTREGISTRY_H
#define CELLSINTERLINKED_PACKETEVENTREGISTRY_H

namespace PacketEventId {
    const static unsigned short MONITOR_STATE_CHANGE_EVENT = 10u;
}

class PacketEventRegistry {
};

#endif //CELLSINTERLINKED_PACKETEVENTREGISTRY_H
